from data_classes import Shape

# General
EPISODES = 100
VISUALIZE_GAMES = True
FRAME_DELAY = 0.15

# Simulated World
BOARD_TYPE = Shape.Triangle
SIZE = 5
HOLES = set([
    (2, 1),
])

# Actor
ACTOR_LEARNING_RATE = 0.8
ACTOR_DISCOUNT_FACTOR = 0.85
ACTOR_TRACE_DECAY = 0.85

ACTOR_EPSILON = 0.9
ACTOR_EPSILON_DECAY = 0.997

# Critic
CRITIC_LEARNING_RATE = 0.001
CRITIC_DISCOUNT_FACTOR = 0.85
CRITIC_TRACE_DECAY = 0.85

USE_TABLE_CRITIC = False
CRITIC_NN_DIMENSIONS = (15, 20, 30, 5, 1)
