from data_classes import Shape

# General
EPISODES = 250
VISUALIZE_GAMES = False
FRAME_DELAY = 0.15

# Simulated World
BOARD_TYPE = Shape.Diamond
SIZE = 6
HOLES = set([
    (1, 1),
    (5, 1),
    (3, 2),
    (2, 3),
    (0, 0),
])
WINNING_REWARD = 1
LOSING_REWARD = -1
STEP_REWARD = 0

# Actor
ACTOR_LEARNING_RATE = 0.8
ACTOR_DISCOUNT_FACTOR = 0.85
ACTOR_TRACE_DECAY = 0.85

ACTOR_EPSILON = 0.9
ACTOR_EPSILON_DECAY = 0.997

# Critic
CRITIC_LEARNING_RATE = 0.001
CRITIC_DISCOUNT_FACTOR = 0.85
CRITIC_TRACE_DECAY = 0.85

USE_TABLE_CRITIC = True
INPUT_DIMENSION = SIZE ** 2 if BOARD_TYPE == Shape.Diamond else int((SIZE * (SIZE + 1)) / 2)
CRITIC_NN_DIMENSIONS = (INPUT_DIMENSION, 20, 30, 5, 1)
