from data_classes import Shape

# General
EPISODES = 600
VISUALIZE_GAMES = True
FRAME_DELAY = 1

# Simulated World
BOARD_TYPE = Shape.Triangle
SIZE = 4
HOLES = set([
    (1, 1),
])

# Actor
ACTOR_LEARNING_RATE = 0.8
ACTOR_DISCOUNT_FACTOR = 0.85
ACTOR_TRACE_DECAY = 0.85

ACTOR_EPSILON = 1
ACTOR_EPSILON_DECAY = 0.9995

# Critic
CRITIC_LEARNING_RATE = 0.01
CRITIC_DISCOUNT_FACTOR = 0.85
CRITIC_TRACE_DECAY = 0.85

USE_TABLE_CRITIC = True
CRITIC_NN_DIMENSIONS = (10, 20, 1)
