from data_classes import Shape

# General
EPISODES = 1000
VISUALIZE_GAMES = True
FRAME_DELAY = 1

# Simulated World
BOARD_TYPE = Shape.Triangle
SIZE = 4
HOLES = set([
    (1, 1),
])

# Actor
ACTOR_LEARNING_RATE = 0.8
ACTOR_DISCOUNT_FACTOR = 0.95
ACTOR_TRACE_DECAY = 0.95

ACTOR_EPSILON = 1
ACTOR_EPSILON_DECAY = 0.9995

# Critic
CRITIC_LEARNING_RATE = 0.3
CRITIC_DISCOUNT_FACTOR = 0.95
CRITIC_TRACE_DECAY = 0.95

USE_TABLE_CRITIC = False
CRITIC_NN_DIMENSIONS = (10, 5, 1)
